// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hotel.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteHotel = `-- name: DeleteHotel :exec
DELETE FROM hotels
WHERE id = $1
`

func (q *Queries) DeleteHotel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHotel, id)
	return err
}

const findHotelByID = `-- name: FindHotelByID :one
SELECT id, host_id, name, description, property_type, address, city, country, latitude, longitude, price_per_night, currency, star_rating, status, search_vector, created_at, updated_at FROM hotels
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindHotelByID(ctx context.Context, id uuid.UUID) (Hotel, error) {
	row := q.db.QueryRowContext(ctx, findHotelByID, id)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.PropertyType,
		&i.Address,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.PricePerNight,
		&i.Currency,
		&i.StarRating,
		&i.Status,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHotel = `-- name: InsertHotel :one
INSERT INTO hotels (host_id, name, description, property_type, address, city, country, latitude, longitude, price_per_night, currency, star_rating, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, host_id, name, description, property_type, address, city, country, latitude, longitude, price_per_night, currency, star_rating, status, search_vector, created_at, updated_at
`

type InsertHotelParams struct {
	HostID        uuid.UUID      `json:"host_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	PropertyType  string         `json:"property_type"`
	Address       sql.NullString `json:"address"`
	City          string         `json:"city"`
	Country       string         `json:"country"`
	Latitude      sql.NullString `json:"latitude"`
	Longitude     sql.NullString `json:"longitude"`
	PricePerNight string         `json:"price_per_night"`
	Currency      string         `json:"currency"`
	StarRating    sql.NullInt32  `json:"star_rating"`
	Status        string         `json:"status"`
}

func (q *Queries) InsertHotel(ctx context.Context, arg InsertHotelParams) (Hotel, error) {
	row := q.db.QueryRowContext(ctx, insertHotel,
		arg.HostID,
		arg.Name,
		arg.Description,
		arg.PropertyType,
		arg.Address,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.PricePerNight,
		arg.Currency,
		arg.StarRating,
		arg.Status,
	)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.PropertyType,
		&i.Address,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.PricePerNight,
		&i.Currency,
		&i.StarRating,
		&i.Status,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHotels = `-- name: ListHotels :many
SELECT id, host_id, name, description, property_type, address, city, country, latitude, longitude, price_per_night, currency, star_rating, status, search_vector, created_at, updated_at FROM hotels
WHERE status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListHotels(ctx context.Context) ([]Hotel, error) {
	rows, err := q.db.QueryContext(ctx, listHotels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.PropertyType,
			&i.Address,
			&i.City,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.PricePerNight,
			&i.Currency,
			&i.StarRating,
			&i.Status,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHotel = `-- name: UpdateHotel :one
UPDATE hotels
SET
    name            = $2,
    description     = $3,
    property_type   = $4,
    address         = $5,
    city            = $6,
    country         = $7,
    latitude        = $8,
    longitude       = $9,
    price_per_night = $10,
    currency        = $11,
    star_rating     = $12,
    status          = $13
WHERE id = $1
RETURNING id, host_id, name, description, property_type, address, city, country, latitude, longitude, price_per_night, currency, star_rating, status, search_vector, created_at, updated_at
`

type UpdateHotelParams struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	PropertyType  string         `json:"property_type"`
	Address       sql.NullString `json:"address"`
	City          string         `json:"city"`
	Country       string         `json:"country"`
	Latitude      sql.NullString `json:"latitude"`
	Longitude     sql.NullString `json:"longitude"`
	PricePerNight string         `json:"price_per_night"`
	Currency      string         `json:"currency"`
	StarRating    sql.NullInt32  `json:"star_rating"`
	Status        string         `json:"status"`
}

func (q *Queries) UpdateHotel(ctx context.Context, arg UpdateHotelParams) (Hotel, error) {
	row := q.db.QueryRowContext(ctx, updateHotel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PropertyType,
		arg.Address,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.PricePerNight,
		arg.Currency,
		arg.StarRating,
		arg.Status,
	)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.PropertyType,
		&i.Address,
		&i.City,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.PricePerNight,
		&i.Currency,
		&i.StarRating,
		&i.Status,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
