// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hotel_images.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteHotelImage = `-- name: DeleteHotelImage :exec
DELETE FROM hotel_images
WHERE id = $1
`

func (q *Queries) DeleteHotelImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHotelImage, id)
	return err
}

const insertHotelImage = `-- name: InsertHotelImage :one
INSERT INTO hotel_images (hotel_id, url, alt, description, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, hotel_id, url, alt, description, position, created_at
`

type InsertHotelImageParams struct {
	HotelID     uuid.UUID      `json:"hotel_id"`
	Url         string         `json:"url"`
	Alt         sql.NullString `json:"alt"`
	Description sql.NullString `json:"description"`
	Position    int32          `json:"position"`
}

func (q *Queries) InsertHotelImage(ctx context.Context, arg InsertHotelImageParams) (HotelImage, error) {
	row := q.db.QueryRowContext(ctx, insertHotelImage,
		arg.HotelID,
		arg.Url,
		arg.Alt,
		arg.Description,
		arg.Position,
	)
	var i HotelImage
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.Url,
		&i.Alt,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listImagesByHotelID = `-- name: ListImagesByHotelID :many
SELECT id, hotel_id, url, alt, description, position, created_at FROM hotel_images
WHERE hotel_id = $1
ORDER BY position DESC
`

func (q *Queries) ListImagesByHotelID(ctx context.Context, hotelID uuid.UUID) ([]HotelImage, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByHotelID, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HotelImage
	for rows.Next() {
		var i HotelImage
		if err := rows.Scan(
			&i.ID,
			&i.HotelID,
			&i.Url,
			&i.Alt,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
