// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Hotel struct {
	ID            uuid.UUID      `json:"id"`
	HostID        uuid.UUID      `json:"host_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	PropertyType  string         `json:"property_type"`
	Address       sql.NullString `json:"address"`
	City          string         `json:"city"`
	Country       string         `json:"country"`
	Latitude      sql.NullString `json:"latitude"`
	Longitude     sql.NullString `json:"longitude"`
	PricePerNight string         `json:"price_per_night"`
	Currency      string         `json:"currency"`
	StarRating    sql.NullInt32  `json:"star_rating"`
	Status        string         `json:"status"`
	SearchVector  interface{}    `json:"search_vector"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type HotelImage struct {
	ID          uuid.UUID      `json:"id"`
	HotelID     uuid.UUID      `json:"hotel_id"`
	Url         string         `json:"url"`
	Alt         sql.NullString `json:"alt"`
	Description sql.NullString `json:"description"`
	Position    int32          `json:"position"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	RevokedAt    sql.NullTime   `json:"revoked_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	FullName  string         `json:"full_name"`
	Role      string         `json:"role"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
