// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE refresh_token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, refreshToken)
	return err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT id, user_id, refresh_token, ip_address, user_agent, expires_at, created_at, revoked_at FROM sessions
WHERE refresh_token = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) FindSessionByToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (user_id, refresh_token, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token, ip_address, user_agent, expires_at, created_at, revoked_at
`

type InsertSessionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.UserID,
		arg.RefreshToken,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
